apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.minerva.global.secrets.name }}
type: Opaque
stringData:
  awsAccessKeyId: "{{ .Values.minerva.secrets.awsAccessKeyId }}"
  awsSecretAccessKey: "{{ .Values.minerva.secrets.awsSecretAccessKey }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.minerva.gitlab.secret.name }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.minerva.secrets.gitlab.registryData }}
